import type { Metadata } from "next";
import { Exo_2 } from 'next/font/google'
import "./globals.css";

const exo2 = Exo_2({
  weight: ['200', '300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-MX" className="dark bg-black">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${exo2.className} text-white dark text-foreground bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
